steps:
- name: gcr.io/cloud-builders/docker
  args: ['build', '-t', 'gcr.io/firstcloudrun-354014/google-cloud-run:$SHORT_SHA', '.']
- name: gcr.io/cloud-builders/docker
  args: ['push', 'gcr.io/firstcloudrun-354014/google-cloud-run:$SHORT_SHA']
